- hosts: localhost
  gather_facts: no
  tasks:
    - name: define list
      set_fact:
        list_a: [3, 10, 11, 9, 6, 8]

    - name: sort list
      set_fact:
        sorted_list_a: "{{ list_a | sort }}"
        #sorted_list_a: "{{ list_a | sort(reverse=True) }}"

    - debug: var=sorted_list_a

    # the list’s last element
    - name: output
      debug:
        msg: "{{ sorted_list_a[-1] }}" # 11
