---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html
# https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_loops.html

# loop
# with_<lookup>
# until


# standard loops
- hosts: localhost
  tasks:
    - block:
      - name: execute uname command
        shell: uname -n
        delegate_to: "{{ item }}"
        delegate_facts: false
        loop:
          - target1
          - target2
      - name: post_tasks
        include_tasks: post_tasks.yml
      when: '"xxxx" in type'




# loop + range (with_sequence)
- hosts: localhost
  tasks:
  - name: range
    debug:
      msg: "{{ 'dir_%02d' | format(item) }}"
    loop: "{{ range(0, 4)|list }}"



