---
# loop with registered variables, and matching item add to list.

- hosts: localhost
  gather_facts: no
  vars:
    match_list: []

  tasks:
    - name: read file
      shell: cat foo.txt
      register: result
      changed_when: false

    - name: make match list
      set_fact:
        match_list: "{{ match_list + [((my_idx+1)|string).zfill(2) + ' ' + line] }}"
      loop: "{{ result.stdout_lines }}"
      loop_control:
        loop_var: line
        index_var: my_idx
      when: line is match('^FooVar\s.*$')

    - debug: var=match_list
    - debug: var=match_list|length
    
    - name: print match list
      debug:
        msg: "{{ match_list }}"
