---
# replace text in a string with regex
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html
# https://docs.python.org/3.8/library/re.html

- hosts: localhost
  gather_facts: no
  vars:
    str: "Target IP Address: 127.22.4.1 xxxx"
  tasks:
    - debug:
        #Extract IP Address
        msg: "{{ str | regex_replace('^.*Address:\\s([\\d.]{1,})\\s[a-z]*$', '\\1') }}"



---
# Convert "ansible" to "able"
{{ 'ansible' | regex_replace('^a.*i(.*)$', 'a\\1') }}
# => 'able'

# Convert "foobar" to "bar"
{{ 'foobar' | regex_replace('^f.*o(.*)$', '\\1') }}
# => 'bar'

# Convert "localhost:80" to "localhost, 80" using named groups
{{ 'localhost:80' | regex_replace('^(?P<host>.+):(?P<port>\\d+)$', '\\g<host>, \\g<port>') }}
# => 'localhost, 80'

# Convert "localhost:80" to "localhost"
{{ 'localhost:80' | regex_replace(':80') }}
# => 'localhost'

# Comment all lines that end with "ar"
{{ 'CAR\ntar\nfoo\nbar\n' | regex_replace('^(.ar)$', '#\\1', multiline=True, ignorecase=True) }}
# => '#CAR\n#tar\nfoo\n#bar\n'
---

# extract_2nd_octet: "{{ ansible_ssh_host | regex_replace('^\\d{1,}\\.(\\d{1,})\\.\\d{1,}\\.\\d{1,}', '\\1') }}"


