---

- hosts: localhost
  gather_facts: false
  vars:
    users:
      - user1
        - "111"
      - user2
        - "222"
      - user3
        - "333"
      - user4
        - "444"
      - user5
        - "555"
  tasks:
    - name: select match
      debug:
        msg: "{{ users | select('match', '.+[3-4]') | list }}"
