- hosts: localhost
  gather_facts: no
  vars:
    include_newlines: |  # |- Remove the last newline 
                exactly as you see
                will appear these three
                lines of poetry

    fold_newlines: >  # >- Remove the last newline 
                this is really a
                single line of text
                despite appearances

    fold_some_newlines: >
        a
        b

        c
        d
          e
        f

    fold_same_newlines: "a b\nc d\n  e\nf\n"

  tasks:
    - name: Literal Block Scalar  # include the newlines and any trailing spaces
      debug:
        msg: "{{ include_newlines }}"

    - name: Folded Block Scalar  # fold newlines to spaces
      debug:
        msg: "{{ fold_newlines }}"

    - name: enforce a newline to be kept
      debug:
        msg: "{{ fold_some_newlines }}"

    - name: enforce a newline to be kept
      debug:
        msg: "{{ fold_same_newlines }}"
