---

- hosts: localhost
  gather_facts: no

  tasks:
    - read_csv:
        path: foo.csv
        fieldnames: col1,col2,col3,col4,col5,col6
      register: csv

    - assert:
        that:
          - item.col1|regex_search('^[a-zA-Z0-9]{7}$')
          - item.col2|regex_search('^[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{1,3}$')
          - item.col3 in ["staging", "production"]
          - item.col4|int <= 100
          - item.col4|int >= 0
          - item.col5 != ''
          - "'xxx' in item.col6"
        fail_msg: "invalid data"
        success_msg: "passed!"
        quiet: true
      with_items: "{{ csv.list }}"
