---
# This module asserts that given expressions are true with an optional custom message.
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html

- hosts: localhost
  gather_facts: no

  tasks:
    - name: Input data validation
      block:
        - name: Input data validation
          assert:
            that:
              - ip_address is match('^[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{1,3}$')
              - var1 is defined and user != ""
              - var2 in ["staging", "production"]
            fail_msg: "The specified input data is invalid."
            quiet: false
          register: input_assert
          ignore_errors: true
        - name: Output Error Msg
          block:
            - name: If failed to assert input data
              debug:
                msg: "{{ return_msg }}"
            - name: Failure with Error Msg
              fail:
          when: input_assert.failed
          
