---
# This module asserts that given expressions are true with an optional custom message.
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assert_module.html

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Input data validation
      block:
        - name: Input data validation
          assert:
            that:
              - var1 is defined and user != ""
              - "'reject' in result.stdout"
              - var2 in ["staging", "production"]
              - ip_address is match('^[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{1,3}$')
            fail_msg: "The specified input data is invalid."
            success_msg: "PASS"  # added in Ansible 2.7
            quiet: false  # added in Ansible 2.8
          register: input_assert



# -------------------------------------
# assign a list to 'that:' Parameter
# -------------------------------------
# vars file
pb1:
  - var1 in ['apple', 'lemon', 'berry']
  - "'foo' in result.stdout"
  - number_of_the_counting == 3
pb2:
  - var1 is match('^[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{2,3}\.[0-9]{1,3}$')
  - my_param <= 100
  - my_param >= 0

# play task
  - name: input data validation2
    assert:
      that:
        "{{ lookup('vars', pb) }}"
        fail_msg: "The specified input data is invalid."
        success_msg: "Input data validation PASS!"
        quiet: False

