---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-sequence

- hosts: localhost
  gather_facts: no

  tasks:
  - name: with_sequence
    debug:
      msg: "{{ item }}"
    with_sequence: start=0 end=10 stride=1 format=dir_%02d
    #with_sequence: start=20 end=0 stride=-1 format=dir_%02d
